# vim: ts=2:sw=2:sts=2:et:ft=yaml
# -*- mode: yaml; yaml-indent-offset: 2; indent-tabs-mode: nil; -*-
---

namespace: o0_o
name: core
version: 0.1.0
readme: README.md
authors:
  - oØ.o (@o0-o)
description: >
  Cross-platform command execution primitives for Ansible.
license: GPL-3.0-or-later
tags:
  - collection
  - core
  - command
  - execution
  - cross-platform
dependencies:
  o0_o.posix: '>=1.0.0'
  o0_o.utils: '>=2.0.0'
  o0_o.windows: '>=0.1.0'
  ansible.windows: '>=2.0.0'
repository: https://github.com/o0-o/ansible-collection-core
issues: https://github.com/o0-o/ansible-collection-core/issues
build_ignore:
  - .git
  - .github
  - .venv
  - .direnv
  - .wip
  - .pytest_cache
  - .mypy_cache
  - tests/output
  - __pycache__
