# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
# -*- mode: yaml; yaml-indent-offset: 2; indent-tabs-mode: nil; -*-
---
# GNU General Public License v3.0+
# SPDX-License-Identifier: GPL-3.0-or-later
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
#
# Copyright (c) 2025 oØ.o (@o0-o)
#
# This file is part of the o0_o.core Ansible Collection.

# Install localhost dependencies

- name: Install pip requirements on localhost
  ansible.builtin.pip:
    requirements: "{{ role_path }}/../../requirements.txt"
    state: present
  delegate_to: localhost
  run_once: true

- name: Install platform collections on localhost
  ansible.builtin.command:
    argv: >-
      {{ ['ansible-galaxy', 'collection', 'install', 'o0_o.' ~ item]
         + (o0_core_update_dependencies | ternary(['--upgrade'], [])) }}
  register: install_collection_reg
  delegate_to: localhost
  run_once: true
  changed_when: "'was installed' in install_collection_reg['stdout']"
  loop: "{{ query('o0_o.core.platform', group='all') }}"

# Install remote host dependencies

# None
